site_name: Rinkhals Documentation
site_url: https://jbatonnet.github.io/Rinkhals/

repo_url: https://github.com/jbatonnet/Rinkhals
repo_name: jbatonnet/Rinkhals
edit_uri: edit/master/docs/docs/

copyright: MIT License

theme:
  name: material

  favicon: assets/icon.png
  logo: assets/icon.png

  palette:   
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - toc.follow
    - toc.integrate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jbatonnet/Rinkhals

plugins:
  - search
  - mkdocs-nav-weight
  - glightbox

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - md_in_html
  - toc:
      toc_depth: 3
      permalink: ¶
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
